SELECT 
    C.NAME 'COLUMN NAME',
    T.NAME 'DATA TYPE',
    C.MAX_LENGTH 'MAX LENGTH',
    C.PRECISION ,
    C.SCALE ,
    C.IS_NULLABLE,
    ISNULL(I.IS_PRIMARY_KEY, 0) 'PRIMARY KEY'
FROM SYS.COLUMNS C
INNER JOIN SYS.TYPES T ON C.USER_TYPE_ID = T.USER_TYPE_ID
LEFT OUTER JOIN SYS.INDEX_COLUMNS IC ON IC.OBJECT_ID = C.OBJECT_ID AND IC.COLUMN_ID = C.COLUMN_ID
LEFT OUTER JOIN SYS.INDEXES I ON IC.OBJECT_ID = I.OBJECT_ID AND IC.INDEX_ID = I.INDEX_ID
WHERE C.OBJECT_ID = OBJECT_ID('table_name')
